### ISSUE TITLE
`go get golang.org/x/tools` is not needed?

### ISSUE THREAD

**Issue by xyproto** [tardisgo/tardisgo#36]
Hi,

Here's what happens when I try to install tardisgo:

```
~% go get golang.org/x/tools
package golang.org/x/tools
	imports golang.org/x/tools
	imports golang.org/x/tools: no buildable Go source files in /home/alexander/go/src/golang.org/x/tools
1~% echo $GOPATH
/home/alexander/go
~% rm -rf ~/go/src/golang.org
~% go get golang.org/x/tools 
package golang.org/x/tools
	imports golang.org/x/tools
	imports golang.org/x/tools: no buildable Go source files in /home/alexander/go/src/golang.org/x/tools
1~% go get -u github.com/tardisgo/tardisgo
~% 
```

(`1~%` is my prompt and means that errorcode 1 was returned, while `~%` means that errorcode 0 was returned).

This is on 64-bit Arch Linux with go 1.4.1.

These files are present in `/usr/lib/go/pkg/tool/linux_amd64/`:

`5a 5c 5g 5l 6a 6c 6g 6l 8a 8c 8g 8l addr2line api cgo cover dist fix nm objdump pack pprof vet yacc`

Does this mean that `go get golang.org/x/tools` is not needed when installing tardisgo on Arch Linux?

Best regards,
Alexander F Rødseth

**Comment by elliott5** [comment]
First, thank you for taking an interest in this project Alexander, I'm working on it full-time at the moment so it is changing a lot at the moment I'm afraid.

The error is because the golang.org/x/tools has no code at the top level, although a great deal below. The ones used are all in: 	"golang.org/x/tools/go/*"
I'll change the instructions to only go get that part of the tree, and point out that an error is returned next time I push.

**Comment by xyproto** [comment]
Thanks for updating the documentation. It's a really cool project. Best of luck with the further development of tardisgo!
