### ISSUE TITLE
Question: Is there any plan to support other standard library?

### ISSUE THREAD

**Issue by hajimehoshi** [tardisgo/tardisgo#37]
Now TardisGo supports a limited set of standard library. I was wondering if you have a plan to support the rest. Ideally, it would be wonderful if most existing Go programs worked with TardisGo on the web browsers without fixing.

**Comment by elliott5** [comment]
Yes. I hope that TARDIS go will eventually be able to support most of the standard library.

Because of the need to work in all of the different target languages, it may be a slightly smaller sub-set of the standard library than [GopherJS supports](https://github.com/gopherjs/gopherjs/blob/master/doc/packages.md).

I am gradually adding new working standard packages, fixing bugs along the way as I do...

**Comment by hajimehoshi** [comment]
Thank you for the reply! I'm looking forward to it.

As this is not a task but a question, I'll close this issue.
